/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import jpl.Prolog;

/**
 *
 * @author Alejandro
 */
public class Registro extends javax.swing.JFrame {

    /**
     * Creates new form Registro
     */
    
    Prolog prolog;
    public String nombre, gusto, musica, comida, listaGustos = "", listaComida = "", listaMusica = "";
    
    public Registro() {
        initComponents();
    }
    
    public Registro(Prolog prolog) {
        initComponents();
        this.prolog = prolog;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtnAtras = new javax.swing.JButton();
        jlbNombre = new javax.swing.JLabel();
        jtfNombre = new javax.swing.JTextField();
        jlbAddGusto = new javax.swing.JLabel();
        jtfGusto = new javax.swing.JTextField();
        jbtnGusto = new javax.swing.JButton();
        jbtnNombre = new javax.swing.JButton();
        jlbAddMusica = new javax.swing.JLabel();
        jtfMusica = new javax.swing.JTextField();
        jbtnMusica = new javax.swing.JButton();
        jlbAddComida = new javax.swing.JLabel();
        jtfComida = new javax.swing.JTextField();
        jbtnComida = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jlistMusica = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jlistComida = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jlistGustos = new javax.swing.JList<>();
        jbtnGuardar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jcbSexo = new javax.swing.JComboBox<>();
        jlbMusica = new javax.swing.JLabel();
        jlbComida = new javax.swing.JLabel();
        jlbTitle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tinder Chafa - Registro");
        setPreferredSize(new java.awt.Dimension(960, 640));
        setResizable(false);

        jbtnAtras.setText("Atrás");
        jbtnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAtrasActionPerformed(evt);
            }
        });

        jlbNombre.setText("Nombre:");

        jlbAddGusto.setText("Agregar Gusto");

        jbtnGusto.setText("+");
        jbtnGusto.setEnabled(false);
        jbtnGusto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnGustoActionPerformed(evt);
            }
        });

        jbtnNombre.setText("+");
        jbtnNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNombreActionPerformed(evt);
            }
        });

        jlbAddMusica.setText("Agregar Musica");

        jbtnMusica.setText("+");
        jbtnMusica.setEnabled(false);
        jbtnMusica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnMusicaActionPerformed(evt);
            }
        });

        jlbAddComida.setText("Agregar Comida");

        jbtnComida.setText("+");
        jbtnComida.setEnabled(false);
        jbtnComida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnComidaActionPerformed(evt);
            }
        });

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jlistMusica.setModel(new DefaultListModel ());
        jScrollPane1.setViewportView(jlistMusica);

        jlistComida.setModel(new DefaultListModel ());
        jScrollPane2.setViewportView(jlistComida);

        jlistGustos.setModel(new DefaultListModel ());
        jScrollPane3.setViewportView(jlistGustos);

        jbtnGuardar.setText("Guardar");
        jbtnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnGuardarActionPerformed(evt);
            }
        });

        jLabel1.setText("Gustos:");

        jLabel2.setText("Sexo:");

        jcbSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hombre", "Mujer" }));

        jlbMusica.setText("Musica:");

        jlbComida.setText("Comida:");

        jlbTitle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlbTitle.setText("Registro de Personas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane3)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jlbAddGusto))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jtfGusto, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtnGusto))
                            .addComponent(jcbSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jlbAddMusica)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtfMusica, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jbtnMusica))
                                    .addComponent(jlbMusica))
                                .addGap(0, 26, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jlbComida)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jlbAddComida)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jtfComida, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jbtnComida))))
                        .addGap(275, 275, 275))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jlbNombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlbTitle)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jtfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtnNombre)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbtnAtras)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jbtnGuardar)
                .addGap(312, 312, 312))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbtnAtras)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbTitle)
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbNombre)
                    .addComponent(jtfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnNombre)
                    .addComponent(jLabel2)
                    .addComponent(jcbSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)
                    .addComponent(jSeparator2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlbAddGusto)
                            .addComponent(jtfGusto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtnGusto)
                            .addComponent(jlbAddComida)
                            .addComponent(jtfComida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtnComida)
                            .addComponent(jlbAddMusica)
                            .addComponent(jtfMusica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtnMusica))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jlbMusica)
                                .addGap(17, 17, 17)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jlbComida)
                                .addGap(22, 22, 22)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(27, 27, 27)
                .addComponent(jbtnGuardar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAtrasActionPerformed
        this.dispose();
        index menu = new index(prolog);
        menu.setLocationRelativeTo(null);
        menu.setVisible(true);
    }//GEN-LAST:event_jbtnAtrasActionPerformed

    
    //Codigo para agregar nombre de persona
    private void jbtnNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNombreActionPerformed
        jbtnGusto.setEnabled(true);
        jbtnMusica.setEnabled(true);
        jbtnComida.setEnabled(true);
        jbtnNombre.setEnabled(false);
        jtfNombre.setEnabled(false);
        nombre = jtfNombre.getText();
        prolog.guardaPersonas(jcbSexo.getSelectedItem().toString(), nombre);
        //prolog.getGustos(jtfNombre.getText());
    }//GEN-LAST:event_jbtnNombreActionPerformed

    private void jbtnGustoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnGustoActionPerformed
        String gusto = jtfGusto.getText();
        jtfGusto.setText("");
        DefaultListModel lmg  = (DefaultListModel) jlistGustos.getModel();
        lmg.addElement(gusto);
        listaGustos = listaGustos + gusto + ",";
    }//GEN-LAST:event_jbtnGustoActionPerformed

    private void jbtnMusicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnMusicaActionPerformed
        String musica = jtfMusica.getText();
        jtfMusica.setText("");
        DefaultListModel lmm  = (DefaultListModel) jlistMusica.getModel();
        lmm.addElement(musica);
        listaMusica = listaMusica + musica + ",";
    }//GEN-LAST:event_jbtnMusicaActionPerformed

    private void jbtnComidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnComidaActionPerformed
        String comida = jtfComida.getText();
        jtfComida.setText("");
        DefaultListModel lmc  = (DefaultListModel) jlistComida.getModel();
        lmc.addElement(comida);
        listaComida = listaComida + comida + ",";
    }//GEN-LAST:event_jbtnComidaActionPerformed

    private void jbtnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnGuardarActionPerformed
        listaGustos = listaGustos.substring(0,listaGustos.length() - 1);
        listaMusica = listaMusica.substring(0,listaMusica.length() - 1);
        listaComida = listaComida.substring(0,listaComida.length() - 1);
        prolog.guardaGustos(nombre, listaGustos);
        prolog.guardaMusica(nombre, listaMusica);
        prolog.guardaComida(nombre, listaComida);
    }//GEN-LAST:event_jbtnGuardarActionPerformed
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton jbtnAtras;
    private javax.swing.JButton jbtnComida;
    private javax.swing.JButton jbtnGuardar;
    private javax.swing.JButton jbtnGusto;
    private javax.swing.JButton jbtnMusica;
    private javax.swing.JButton jbtnNombre;
    private javax.swing.JComboBox<String> jcbSexo;
    private javax.swing.JLabel jlbAddComida;
    private javax.swing.JLabel jlbAddGusto;
    private javax.swing.JLabel jlbAddMusica;
    private javax.swing.JLabel jlbComida;
    private javax.swing.JLabel jlbMusica;
    private javax.swing.JLabel jlbNombre;
    private javax.swing.JLabel jlbTitle;
    private javax.swing.JList<String> jlistComida;
    private javax.swing.JList<String> jlistGustos;
    private javax.swing.JList<String> jlistMusica;
    private javax.swing.JTextField jtfComida;
    private javax.swing.JTextField jtfGusto;
    private javax.swing.JTextField jtfMusica;
    private javax.swing.JTextField jtfNombre;
    // End of variables declaration//GEN-END:variables
}
